In [1]:
#project 1

In [ ]:
pip install ipympl


ModuleNotFoundError: No module named 'ipympl'

In [ ]:
%matplotlib widget

In [ ]:
#pip install matplotlib seaborn # type: ignore
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns  # type: ignore
from sklearn.model_selection import train_test_split
import numpy as np

In [ ]:
# Load the CSV file
data = pd.read_csv('iris.csv')
data.columns = data.columns.str.replace('"', '')  # Clean column names

# Display the first few rows of the dataset
print("Head of the dataset:")
print(data.head())

Head of the dataset:
   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa


In [ ]:
# Set plot style
sns.set(style="whitegrid")

# Scatter plot for Sepal Length and Sepal Width
plt.figure(figsize=(10, 5))
sns.scatterplot(data=data, x="sepal.length", y="sepal.width", hue="variety", palette="Set1")
plt.title("Sepal Length & Sepal Width")
plt.show()

# Scatter plot for Petal Length and Petal Width
plt.figure(figsize=(10, 5))
sns.scatterplot(data=data, x="petal.length", y="petal.width", hue="variety", palette="Set1")
plt.title("Petal Length & Petal Width")
plt.show()

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
# Encode the 'variety' column as numerical labels
data['variety'] = data['variety'].astype('category').cat.codes

# Define the feature matrix X and target vector y
X = data.drop(columns=['variety'])
y = data['variety']

# Specify the class to be removed (e.g., 0, 1, or 2)
class_to_remove = 0  # Change this value to remove a different class

# Filter out the specified class
mask = y != class_to_remove
X = X[mask]
y = y[mask]

# Reset the index after filtering
X.reset_index(drop=True, inplace=True)
y.reset_index(drop=True, inplace=True)

# Split the dataset into training and temporary sets (70% training, 30% temporary)
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

# Split the temporary set into validation and test sets (15% each of the original data)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp,
    test_size=0.5,
    random_state=42,
    stratify=y_temp
)

In [ ]:
# Display the shapes of the resulting datasets
print("Shapes of the datasets:")
print(f"X_train: {X_train.shape}, y_train: {y_train.shape}")
print(f"X_val: {X_val.shape}, y_val: {y_val.shape}")
print(f"X_test: {X_test.shape}, y_test: {y_test.shape}")

# Display the unique classes in the remaining data
classes = np.unique(y)
print(f"Remaining classes after filtering: {classes}")

Shapes of the datasets:
X_train: (70, 4), y_train: (70,)
X_val: (15, 4), y_val: (15,)
X_test: (15, 4), y_test: (15,)
Remaining classes after filtering: [1 2]


Now here we need to start the algarithm part:

In [ ]:
%matplotlib inline
import random
import torch
from d2l import torch as d2l

In [ ]:
# Convert data to PyTorch tensors

X_train = torch.tensor(X_train.values, dtype=torch.float32)
y_train = torch.tensor(y_train.values, dtype=torch.float32).view(-1, 1)
X_val = torch.tensor(X_val.values, dtype=torch.float32)
y_val = torch.tensor(y_val.values, dtype=torch.float32).view(-1, 1)
X_test = torch.tensor(X_test.values, dtype=torch.float32)
y_test = torch.tensor(y_test.values, dtype=torch.float32).view(-1, 1)

In [ ]:
y

0     1
1     1
2     1
3     1
4     1
     ..
95    2
96    2
97    2
98    2
99    2
Name: variety, Length: 100, dtype: int8

In [ ]:
def data_iter(batch_size, features, labels):
    num_examples = len(features)
    indices = list(range(num_examples))
    # 这些样本是随机读取的，没有特定的顺序
    random.shuffle(indices)
    for i in range(0, num_examples, batch_size):
        batch_indices = torch.tensor(
            indices[i: min(i + batch_size, num_examples)])
        yield features[batch_indices], labels[batch_indices]


In [ ]:
batch_size = 20
for i, j in data_iter(batch_size, X_train, y_train):
    print(i, '\n', j)
    break

tensor([[6.9000, 3.1000, 5.4000, 2.1000],
        [6.3000, 3.4000, 5.6000, 2.4000],
        [6.7000, 3.3000, 5.7000, 2.1000],
        [5.9000, 3.0000, 5.1000, 1.8000],
        [6.3000, 2.3000, 4.4000, 1.3000],
        [5.8000, 2.7000, 3.9000, 1.2000],
        [5.5000, 2.5000, 4.0000, 1.3000],
        [7.2000, 3.6000, 6.1000, 2.5000],
        [5.6000, 2.5000, 3.9000, 1.1000],
        [7.7000, 2.6000, 6.9000, 2.3000],
        [5.7000, 3.0000, 4.2000, 1.2000],
        [6.3000, 2.8000, 5.1000, 1.5000],
        [7.7000, 3.8000, 6.7000, 2.2000],
        [6.7000, 3.1000, 5.6000, 2.4000],
        [7.7000, 2.8000, 6.7000, 2.0000],
        [5.8000, 2.7000, 4.1000, 1.0000],
        [6.2000, 2.9000, 4.3000, 1.3000],
        [5.7000, 2.8000, 4.5000, 1.3000],
        [6.4000, 2.9000, 4.3000, 1.3000],
        [5.6000, 2.7000, 4.2000, 1.3000]]) 
 tensor([[2.],
        [2.],
        [2.],
        [2.],
        [1.],
        [1.],
        [1.],
        [2.],
        [1.],
        [2.],
        [1.],
   

In [ ]:
#W,b

In [ ]:
def linreg(X, w, b): #@save
    """Linear Reression"""
    return torch.matmul(X, w) + b

In [ ]:
def squared_loss(y_hat, y): #@save
    """MSL"""
    return (y_hat - y.reshape(y_hat.shape)) ** 2 / 2

In [ ]:
def sgd(params, lr, batch_size): #@save
    """⼩批量随机梯度下降"""
    with torch.no_grad():
        for param in params:
            param -= lr * param.grad / batch_size
            param.grad.zero_()

In [ ]:
#training
lr = 0.03
num_epochs = 20
net = linreg
loss = squared_loss
features, labels = X_train,y_train
W = torch.normal(0, 3, size=(4,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [ ]:
for epoch in range(num_epochs):
    for X, y in data_iter(batch_size, features, labels):
        l = loss(net(X, W, b), y) # X和y的⼩批量损失
        # 因为l形状是(batch_size,1)，⽽不是⼀个标量。l中的所有元素被加到⼀起，
        # 并以此计算关于[w,b]的梯度
        l.sum().backward()
        sgd([W, b], lr, batch_size) # 使⽤参数的梯度更新参数
        with torch.no_grad():
            train_l = loss(net(features, W, b), labels)
            print(f'epoch {epoch + 1}, loss {float(train_l.mean()):f}')


epoch 1, loss 185.266327
epoch 1, loss 331.731506
epoch 1, loss 397.968628
epoch 1, loss 45.787136
epoch 2, loss 123.484627
epoch 2, loss 238.872543
epoch 2, loss 412.597443
epoch 2, loss 1.606910
epoch 3, loss 1.677158
epoch 3, loss 1.838759
epoch 3, loss 1.894463
epoch 3, loss 1.497776
epoch 4, loss 1.493491
epoch 4, loss 1.699766
epoch 4, loss 1.491362
epoch 4, loss 2.743134
epoch 5, loss 4.978352
epoch 5, loss 16.709673
epoch 5, loss 34.526619
epoch 5, loss 1.711254
epoch 6, loss 1.437029
epoch 6, loss 1.625804
epoch 6, loss 1.477317
epoch 6, loss 1.452303
epoch 7, loss 2.152105
epoch 7, loss 2.534699
epoch 7, loss 1.626495
epoch 7, loss 1.403200
epoch 8, loss 1.851508
epoch 8, loss 2.419625
epoch 8, loss 2.474545
epoch 8, loss 1.504908
epoch 9, loss 1.368582
epoch 9, loss 1.401827
epoch 9, loss 3.331897
epoch 9, loss 1.698328
epoch 10, loss 1.737421
epoch 10, loss 2.099036
epoch 10, loss 4.295419
epoch 10, loss 1.548517
epoch 11, loss 1.472638
epoch 11, loss 3.043408
epoch 11, los

In [ ]:
W,b

(tensor([[ 2.5245],
         [-5.5660],
         [-0.1942],
         [ 1.3023]], requires_grad=True),
 tensor([-0.1411], requires_grad=True))

In [ ]:
# Enable interactivity in Jupyter


import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np

# Extract learned weights and bias
W_ = W.detach().numpy().flatten()
b_ = b.item()

# Convert training data back to NumPy for visualization
X_train_np = X_train.numpy()
y_train_np = y_train.numpy().flatten()

# Define a function to create an interactive 3D plot with Matplotlib
def plot_interactive_3d(features, feature_names, W, b, y, title):
    # Extract the chosen features for x and y axes
    x_vals = features[:, 0]
    y_vals = features[:, 1]
    z_vals = y

    # Create a meshgrid for the regression plane
    x_grid, y_grid = np.meshgrid(
        np.linspace(x_vals.min(), x_vals.max(), 50),
        np.linspace(y_vals.min(), y_vals.max(), 50)
    )
    # Calculate the corresponding z values for the regression plane
    z_grid = W[0] * x_grid + W[1] * y_grid + b

    # Create the plot
    fig = plt.figure(figsize=(12, 8))
    ax = fig.add_subplot(111, projection='3d')

    # 3D scatter plot of the data points
    ax.scatter(x_vals, y_vals, z_vals, color='blue', label='True Values', s=50)

    # Plot the regression plane
    ax.plot_surface(x_grid, y_grid, z_grid, color='red', alpha=0.5, rstride=100, cstride=100)

    # Set labels and title
    ax.set_xlabel(feature_names[0])
    ax.set_ylabel(feature_names[1])
    ax.set_zlabel('Target Value (y)')
    ax.set_title(title)
    ax.legend()

    # Show the plot with interactivity enabled
    plt.show()

# Plot for Sepal Length & Sepal Width (using W[0] and W[1])
plot_interactive_3d(X_train_np[:, :2], ['Sepal Length', 'Sepal Width'], W_[:2], b_, y_train_np, 'Sepal Features with Regression Plane')

# Plot for Petal Length & Petal Width (using W[2] and W[3])
plot_interactive_3d(X_train_np[:, 2:], ['Petal Length', 'Petal Width'], W_[2:], b_, y_train_np, 'Petal Features with Regression Plane')



<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>